services:
  mongodb:
    container-name: pessoas_mongodb
    image: bitnami/mongodb:latest
    restart: always
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - pessoas_mongodb:/bitnami/mongodb
    ports:
      - 27017:27017
    enviroment:
      - MONGO_ROOT_PASSWORD=secure
      - MONGO_ADVERTISED_HOSTNAME=localhost
      - MONGO_REPLICA_SET_MODE=primary
      - MONGO_REPLICA_SET_NAME=rs0
      - MONGO_REPLICA_SET_KEY=replicasetkey123

volumes:
  pessoas_mongodb